# docker-compose.yml
version: '3.8'

services:
  server-ping:
    build:
      context: ./PING
      dockerfile: Dockerfile-ping
    container_name: server-ping
    ports:
      - "4567:4567"
    depends_on:
      - server-registry
      - message-broker
      - gateway

  server-pong:
    build:
      context: ./PONG
      dockerfile: Dockerfile-pong
    container_name: server-pong
    ports:
      - "5372:5372"
    depends_on:
      - server-registry
      - message-broker
      - gateway

  gateway:
    build:
      context: ./GATEWAY
      dockerfile: Dockerfile-gateway
    container_name: gateway
    ports:
      - "8081:8081"
    depends_on:
      - message-broker

  message-broker:
    image: "rabbitmq:management"
    container_name: message-broker
    ports:
      - "5672:5672"
      - "15672:15672"

  server-registry:
    build:
      context: ./REGISTRY
      dockerfile: Dockerfile-registry
    container_name: server-registry
    ports:
      - "8080:8080"
    depends_on:
      - message-broker
